server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zxc85167518
    url: jdbc:mysql://localhost:3306/mybatis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

#所有监控的开始配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点

