server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_bee
    username: root
    password: zxc85167518
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: zxc85167518
        reset-enable: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
